name: ci

on:
    pull_request:
        branches:
            - main
            - addtets
    push:
        branches: [main]

jobs:
    # tests:
    #     name: Tests
    #     runs-on: ubuntu-latest
    #
    #     steps:
    #         - name: Check out code
    #           uses: actions/checkout@v4
    #
    #         - name: Set up Go
    #           uses: actions/setup-go@v5
    #           with:
    #               go-version: "1.25.1"
    #
    #         - name: Run unit tests
    #           run: go test ./... -cover
    #
    #         - name: Install gosec
    #           run: go install github.com/securego/gosec/v2/cmd/gosec@latest
    #
    #         - name: Run gosec
    #           run: gosec ./...

    style:
        name: Style
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: "1.25.1"

            - name: Check formatting
              run: test -z $(go fmt ./...)

            - name: Install staticcheck
              run: go install honnef.co/go/tools/cmd/staticcheck@latest

            - name: Run staticcheck
              run: staticcheck ./...

            # Cache dependencies with the specific key
            - name: Cache dependencies
              id: cache-dependencies
              uses: actions/cache@v4
              with:
                  path: |
                      node_modules
                      ~/.npm
                  key: cache-b69fdd6-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      cache-b69fdd6-${{ runner.os }}-
                      cache-b69fdd6-

            - name: prime-cache-b69fdd6
              run: |
                  if [ "${{ steps.cache-dependencies.outputs.cache-hit }}" == "true" ]; then
                  echo "Cache key: cache-b69fdd6-${{ runner.os }}"
                  fi
